### PR TITLE
feat: element-plus dark mode follow histoire dark mode

### PR DESCRIPTION
**Pull request by BTBMan**

### CODE REVIEW

**Comment by Alkaidcc** [comment]
Hey, @BTBMan  It looks like dark mode doesn't work in neither https://element-plus-interactive-docs.netlify.app/ nor https://deploy-preview-50--element-plus-interactive-docs.netlify.app Is it my problem?

**Comment by BTBMan** [comment]
@Alkaidcc I don't know, It works on my machine. Does it is working on your machine? @FliPPeDround

**Comment by FliPPeDround** [comment]
> @Alkaidcc I don't know, It works on my machine. Does it is working on your machine? @FliPPeDround

I'm OK. Can you provide some pictures? @Alkaidcc

**Comment by Alkaidcc** [comment]
Okay, @FliPPeDround @BTBMan When I visit https://element-plus-interactive-docs.netlify.app/, it's not working, (so weird
gif_capture
- OS: Windows11 22H2
- Browser: Chrome 106.0.5249.119

**Comment by Alkaidcc** [comment]
#53 works well on my machine, you can test it on yours. @BTBMan @FliPPeDround

**Pull request merged**
