### PR TITLE
fix: dark mode #50

### PR DESCRIPTION
**Pull request by Alkaidcc**
fix https://github.com/element-plus/element-plus-interactive-docs/pull/50#issuecomment-1280789864

### CODE REVIEW

**Comment by BTBMan** [comment]
Not works on my machine. Maybe I know how to fix it.

**Comment by BTBMan** [comment]
@Alkaidcc Try it, https://deploy-preview-53--element-plus-interactive-docs.netlify.app/

**Comment by Alkaidcc** [comment]
> 

still not working, I can't figure it out🥲

**Comment by BTBMan** [comment]
So weird! do you have any other browsers?

**Comment by BTBMan** [comment]
I know that. 😆

**Pull request merged**
