### PR TITLE
fix: dark mode #50 #53

### PR DESCRIPTION
**Pull request by BTBMan**
Fix PR #50 #53

### CODE REVIEW

**Comment by BTBMan** [comment]
@Alkaidcc Try this https://deploy-preview-55--element-plus-interactive-docs.netlify.app/

**Comment by FliPPeDround** [comment]
> @Alkaidcc Try this https://deploy-preview-55--element-plus-interactive-docs.netlify.app/

image
Looks like a bit of a problem.

**Comment by BTBMan** [comment]
I realized and I will fix it,

**Comment by BTBMan** [comment]
Try it, @FliPPeDround

**Comment by FliPPeDround** [comment]
> Try it, @FliPPeDround

I have no problem in my machine， @Alkaidcc and you？

**Comment by Alkaidcc** [comment]
> > Try it, @FliPPeDround
> 
> I have no problem in my machine， @Alkaidcc and you？

no problem，thx！🍻

**Pull request merged**
