### PR TITLE
feat: init Skeleton component.

### PR DESCRIPTION
**Pull request by akinoccc**
#7

### CODE REVIEW

**Comment by FliPPeDround** [comment]
It would be nice to have a toggle control for the Animation

**Comment by akinoccc** [comment]
> It would be nice to have a toggle control for the Animation

ok, I'll add it immediately.

**Comment by akinoccc** [comment]
> It would be nice to have a toggle control for the Animation

I done it.

**Comment by FliPPeDround** [comment]
> > It would be nice to have a toggle control for the Animation
> 
> I done it.

great！but, usually we need to put the controls in Controls, not on the page.
image

**Comment by akinoccc** [comment]
> It would be nice to have a toggle control for the Animation
I have put the controls of the Animation in the Controls. Please check again what else I need to modify. Thanks!

**Comment by FliPPeDround** [comment]
> > It would be nice to have a toggle control for the Animation
> > I have put the controls of the Animation in the Controls. Please check again what else I need to modify. Thanks!

thx your PR

**Pull request merged**
