### PR TITLE
feat: init switch component

### PR DESCRIPTION
**Pull request by winchesHe**
init switch component
image
#7

### CODE REVIEW

**Comment by FliPPeDround** [comment]
Thank you for your contribution 🎉

**Comment by Alkaidcc** [comment]
Hi~ @winchesHe I found some problems
1.this line https://github.com/element-plus/element-plus-docs-histoire/blob/070d80d104d76cbacf54b528e0cba387c3b88a3c/src/components/Form/switch.story.vue#L109 should be `"Form/Switch"` ?
2. some typos in your code
image

**Comment by FliPPeDround** [comment]
> Hi~ @winchesHe I found some problems 1.this line
> 
> https://github.com/element-plus/element-plus-docs-histoire/blob/070d80d104d76cbacf54b528e0cba387c3b88a3c/src/components/Form/switch.story.vue#L109
> 
> should be `"Form/Switch"` ?
> 2. some typos in your code
> image

Welcome pr👏

**Comment by winchesHe** [comment]
thx~ Yesterday it was too late, I was a bit careless 🌹

**Comment by winchesHe** [comment]
> Hi~ @winchesHe I found some problems 1.this line
> 
> https://github.com/element-plus/element-plus-docs-histoire/blob/070d80d104d76cbacf54b528e0cba387c3b88a3c/src/components/Form/switch.story.vue#L109
> 
> should be `"Form/Switch"` ?
> 2. some typos in your code
> image

thx~ Yesterday it was too late, I was a bit careless 🌹

**Pull request merged**
