### PR TITLE
feat: init colorPicker component

### PR DESCRIPTION
**Pull request by faga295**
#7

### CODE REVIEW

**Comment by FliPPeDround** [comment]
Suggestion.
- Each Variant should have Controls that correspond to it
- Alpha Variant It doesn't look like you can adjust the size

eg: Alpha Variant Should be able to adjust alpha

**Comment by FliPPeDround** [comment]
And then, thank you so much for your enthusiastic contribution
@faga1

**Comment by faga295** [comment]
seems like we can't dynamicly change alpha attribute, and also in many other el component has the same problem

**Comment by faga295** [comment]
now it can adjust size,and added predefine checkbox, alpha controls would be late, because of its bug

**Pull request merged**
